sudo: false
dist: trusty
language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9
  - rbx-3

matrix:
  allow_failures:
    # Rubinius has a lot of trouble and no large following, so I'm going to
    # allow failures on it until it gets more stable on Travis / Real Life(tm).
    # Let me know if you need it. Patches are welcome!
    - rvm: rbx-3
  fast_finish: true

cache:
  directories:
  - .bundle
  - spec/railsapps/rails_42/.bundle
  - spec/railsapps/rails_42_sprockets_rails_3/.bundle
  - spec/railsapps/rails_50/.bundle
  - spec/railsapps/rails_50_sprockets_4/.bundle
bundler_args: --without guard --path=.bundle
script: "rake"
