sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

matrix:
  fast_finish: true

before_install:
  - gem install bundler # Need for Ruby 2.5: https://github.com/travis-ci/travis-ci/issues/9333

cache:
  directories:
  - .bundle
  - spec/railsapps/rails_42/.bundle
  - spec/railsapps/rails_42_sprockets_rails_3/.bundle
  - spec/railsapps/rails_50/.bundle
  - spec/railsapps/rails_51/.bundle
  - spec/railsapps/rails_52/.bundle
bundler_args: --without guard --path=.bundle
script: "rake"
